#!/bin/bash

aff3ct_path=~/Projects/aff3ct

mkdir -p sc_N/dat/
mkdir -p sc_R/dat/
mkdir -p scl_L/dat/
mkdir -p scl_crc/dat/
mkdir -p ascl_crc/dat/
mkdir -p bp_scan/dat/
mkdir -p scf/dat/

# # SC Rendement 0.5 N varie
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "500" --enc-fb-gen-method "GA"  -K 64    -N "128"   --dec-type "SC" --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_N/dat/SC_128.txt     # --sim-meta "Polar (128,64)      SC"                
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "500" --enc-fb-gen-method "GA"  -K 128   -N "256"   --dec-type "SC" --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_N/dat/SC_256.txt     # --sim-meta "Polar (256,128)     SC"                
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "500" --enc-fb-gen-method "GA"  -K 256   -N "512"   --dec-type "SC" --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_N/dat/SC_512.txt     # --sim-meta "Polar (512,256)     SC"                
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "200" --enc-fb-gen-method "GA"  -K 512   -N "1024"  --dec-type "SC" --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_N/dat/SC_1024.txt    # --sim-meta "Polar (1024,512)    SC"                
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1024  -N "2048"  --dec-type "SC" --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_N/dat/SC_2048.txt    # --sim-meta "Polar (2048,1024)   SC"                
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 2048  -N "4096"  --dec-type "SC" --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_N/dat/SC_4096.txt    # --sim-meta "Polar (4096,2048)   SC"                
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 4096  -N "8192"  --dec-type "SC" --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_N/dat/SC_8192.txt    # --sim-meta "Polar (8192,4096)   SC"                
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 8192  -N "16384" --dec-type "SC" --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_N/dat/SC_16384.txt   # --sim-meta "Polar (16384,8192)  SC"                
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 16384 -N "32768" --dec-type "SC" --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_N/dat/SC_32768.txt   # --sim-meta "Polar (32768,16384) SC"                


# # SC N 2048 Rendement varie 1/8 1/4 3/8 etc...
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 256  -N "2048"   --dec-type "SC"  --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_R/dat/SC_1_8.txt    # --sim-meta "Polar (2048,256)      SC"             
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 512  -N "2048"   --dec-type "SC"  --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_R/dat/SC_2_8.txt    # --sim-meta "Polar (2048,512)      SC"             
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 768  -N "2048"   --dec-type "SC"  --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_R/dat/SC_3_8.txt    # --sim-meta "Polar (2048,768)      SC"             
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1024 -N "2048"   --dec-type "SC"  --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_R/dat/SC_4_8.txt    # --sim-meta "Polar (2048,1024)     SC"             
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1280 -N "2048"   --dec-type "SC"  --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_R/dat/SC_5_8.txt    # --sim-meta "Polar (2048,1280)     SC"             
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1536 -N "2048"   --dec-type "SC"  --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_R/dat/SC_6_8.txt    # --sim-meta "Polar (2048,1536)     SC"             
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1792 -N "2048"   --dec-type "SC"  --dec-implem FAST  --dec-simd INTER --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND > sc_R/dat/SC_7_8.txt    # --sim-meta "Polar (2048,1792)     SC"             

# # SCL N 2048 L varie 2 à 32
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 1  --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" > scl_L/dat/SCL_1.txt                        # --sim-meta "Polar (2048,1723) SCL L=1"            
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 2  --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" > scl_L/dat/SCL_2.txt                        # --sim-meta "Polar (2048,1723) SCL L=2"            
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 4  --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" > scl_L/dat/SCL_4.txt                        # --sim-meta "Polar (2048,1723) SCL L=4"            
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 8  --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" > scl_L/dat/SCL_8.txt                        # --sim-meta "Polar (2048,1723) SCL L=8"            
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 16 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" > scl_L/dat/SCL_16.txt                       # --sim-meta "Polar (2048,1723) SCL L=16"           
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" > scl_L/dat/SCL_32.txt                       # --sim-meta "Polar (2048,1723) SCL L=32"           
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 16-CCITT > scl_crc/dat/SCL_16.txt # --sim-meta "Polar (2048,1723) CA-SCL L=32 CRC 16" 

# # BP - SCAN
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 512  -N "1024"   --dec-type "SCAN" --dec-implem NAIVE  --sim-stop-time 20 --chn-implem FAST --src-type RAND --src-implem FAST -i 1 > bp_scan/dat/SCAN_1.txt                                                                                #--sim-meta "Polar (1024,512) SCAN"           
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 512  -N "1024"   --dec-type "SCAN" --dec-implem NAIVE  --sim-stop-time 20 --chn-implem FAST --src-type RAND --src-implem FAST -i 2 > bp_scan/dat/SCAN_2.txt                                                                                #--sim-meta "Polar (1024,512) SCAN"           
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 512  -N "1024"   --dec-type "SCAN" --dec-implem NAIVE  --sim-stop-time 20 --chn-implem FAST --src-type RAND --src-implem FAST -i 3 > bp_scan/dat/SCAN_3.txt                                                                                #--sim-meta "Polar (1024,512) SCAN"           
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 512  -N "1024"   --dec-type "SCAN" --dec-implem NAIVE  --sim-stop-time 20 --chn-implem FAST --src-type RAND --src-implem FAST -i 4 > bp_scan/dat/SCAN_4.txt                                                                                #--sim-meta "Polar (1024,512) SCAN"           
${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "3.5" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 512  -N "1024"   --dec-type "SCL"  --dec-implem FAST   --sim-stop-time 20 --dec-simd INTRA  --chn-implem FAST --src-implem FAST --src-type RAND --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}"  -L 2  > bp_scan/dat/SCL.txt #--sim-meta "Polar (2048,1723) CA-SCL CRC 4"  

# # SCL N 2048 CRC varie 
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 4-ITU    > scl_crc/dat/SCL_4.txt  # --sim-meta "Polar (2048,1723) CA-SCL CRC 4"       
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 6-ITU    > scl_crc/dat/SCL_6.txt  # --sim-meta "Polar (2048,1723) CA-SCL CRC 6"       
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}"  --crc-poly 8-DVB-S2 > scl_crc/dat/SCL_8.txt # --sim-meta "Polar (2048,1723) CA-SCL CRC 8"       
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 16-CCITT > scl_crc/dat/SCL_16.txt # --sim-meta "Polar (2048,1723) CA-SCL CRC 16"      
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 24-LTEA  > scl_crc/dat/SCL_24.txt # --sim-meta "Polar (2048,1723) CA-SCL CRC 24"      
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 32-GZIP  > scl_crc/dat/SCL_32.txt # --sim-meta "Polar (2048,1723) CA-SCL CRC 32"      

# # ASCL N 2048 CRC varie 
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "ASCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 4-ITU     > ascl_crc/dat/FASCL_4.txt  # --sim-meta "Polar (2048,1723) FASCL CRC 4"        
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "ASCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 6-ITU     > ascl_crc/dat/FASCL_6.txt  # --sim-meta "Polar (2048,1723) FASCL CRC 6"        
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "ASCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 8-DVB-S2  > ascl_crc/dat/FASCL_8.txt  # --sim-meta "Polar (2048,1723) FASCL CRC 8"        
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "ASCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 16-CCITT  > ascl_crc/dat/FASCL_16.txt # --sim-meta "Polar (2048,1723) FASCL CRC 16"       
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "ASCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 24-LTEA   > ascl_crc/dat/FASCL_24.txt # --sim-meta "Polar (2048,1723) FASCL CRC 24"       
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "ASCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 32-GZIP   > ascl_crc/dat/FASCL_32.txt # --sim-meta "Polar (2048,1723) FASCL CRC 32"       

# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "ASCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 4-ITU      --dec-partial-adaptive > ascl_crc/dat/PASCL_4.txt  # --sim-meta "Polar (2048,1723) PASCL CRC 4"        
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "ASCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 6-ITU      --dec-partial-adaptive > ascl_crc/dat/PASCL_6.txt  # --sim-meta "Polar (2048,1723) PASCL CRC 6"        
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "ASCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 8-DVB-S2   --dec-partial-adaptive > ascl_crc/dat/PASCL_8.txt  # --sim-meta "Polar (2048,1723) PASCL CRC 8"        
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "ASCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 16-CCITT   --dec-partial-adaptive > ascl_crc/dat/PASCL_16.txt # --sim-meta "Polar (2048,1723) PASCL CRC 16"       
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "ASCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 24-LTEA    --dec-partial-adaptive > ascl_crc/dat/PASCL_24.txt # --sim-meta "Polar (2048,1723) PASCL CRC 24"       
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "6" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 1723 -N "2048"   --dec-type "ASCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 32 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 32-GZIP    --dec-partial-adaptive > ascl_crc/dat/PASCL_32.txt # --sim-meta "Polar (2048,1723) PASCL CRC 32"       

# # Simus pour SC Flip
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "3.5" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 512 -N "1024"   --dec-type "SC" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND   --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}"     > scf/dat/SC.txt  # --sim-meta "Polar (1024,512) CA-SCL L 2"       
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "3.5" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 512 -N "1024"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 2 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 16-CCITT    > scf/dat/SCL_2.txt  # --sim-meta "Polar (1024,512) CA-SCL L 2"       
# ${aff3ct_path}/build/bin/aff3ct  --sim-type "BFER" -C "POLAR" -m "0" -M "3.5" -s "0.25" -e "100" --enc-fb-gen-method "GA"  -K 512 -N "1024"   --dec-type "SCL" --dec-implem FAST  --dec-simd INTRA --sim-stop-time 20 --chn-implem FAST --src-implem FAST --src-type RAND -L 4 --dec-polar-nodes "{R0,R1,R0L,REP_2-8,REPL}" --crc-poly 16-CCITT    > scf/dat/SCL_4.txt  # --sim-meta "Polar (1024,512) CA-SCL L 4"       
