#!/bin/bash
# N = 256, R = 0.33, L = 16
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 256 -K 84 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC_4}" --sim-pyber "Mesure_Diff_SPC_N_256_R_1_3_L_16_SPC4" > "mesures/Mesure_Diff_SPC_N_256_R_1_3_L_16_SPC4.txt"
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 256 -K 84 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC}" --sim-pyber "Mesure_Diff_SPC_N_256_R_1_3_L_16_SPC4+" > "mesures/Mesure_Diff_SPC_N_256_R_1_3_L_16_SPC4+.txt"
# # N = 1024, R = 0.33, L = 16
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 1024 -K 337 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC_4}" --sim-pyber "Mesure_Diff_SPC_N_1024_R_1_3_L_16_SPC4" > "mesures/Mesure_Diff_SPC_N_1024_R_1_3_L_16_SPC4.txt"
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 1024 -K 337 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC}" --sim-pyber "Mesure_Diff_SPC_N_1024_R_1_3_L_16_SPC4+" > "mesures/Mesure_Diff_SPC_N_1024_R_1_3_L_16_SPC4+.txt"
# # N = 4096, R = 0.33, L = 16
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 4096 -K 1351 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC_4}" --sim-pyber "Mesure_Diff_SPC_N_4096_R_1_3_L_16_SPC4" > "mesures/Mesure_Diff_SPC_N_4096_R_1_3_L_16_SPC4.txt"
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 4096 -K 1351 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC}" --sim-pyber "Mesure_Diff_SPC_N_4096_R_1_3_L_16_SPC4+" > "mesures/Mesure_Diff_SPC_N_4096_R_1_3_L_16_SPC4+.txt"
# # N = 256, R = 0.5, L = 16
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 256 -K 128 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC_4}" --sim-pyber "Mesure_Diff_SPC_N_256_R_1_2_L_16_SPC4" > "mesures/Mesure_Diff_SPC_N_256_R_1_2_L_16_SPC4.txt"
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 256 -K 128 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC}" --sim-pyber "Mesure_Diff_SPC_N_256_R_1_2_L_16_SPC4+" > "mesures/Mesure_Diff_SPC_N_256_R_1_2_L_16_SPC4+.txt"
# # N = 1024, R = 0.5, L = 16
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 1024 -K 512 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC_4}" --sim-pyber "Mesure_Diff_SPC_N_1024_R_1_2_L_16_SPC4" > "mesures/Mesure_Diff_SPC_N_1024_R_1_2_L_16_SPC4.txt"
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 1024 -K 512 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC}" --sim-pyber "Mesure_Diff_SPC_N_1024_R_1_2_L_16_SPC4+" > "mesures/Mesure_Diff_SPC_N_1024_R_1_2_L_16_SPC4+.txt"
# # N = 4096, R = 0.5, L = 16
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 4096 -K 2048 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC_4}" --sim-pyber "Mesure_Diff_SPC_N_4096_R_1_2_L_16_SPC4" > "mesures/Mesure_Diff_SPC_N_4096_R_1_2_L_16_SPC4.txt"
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 4096 -K 2048 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC}" --sim-pyber "Mesure_Diff_SPC_N_4096_R_1_2_L_16_SPC4+" > "mesures/Mesure_Diff_SPC_N_4096_R_1_2_L_16_SPC4+.txt"
# # N = 256, R = 0.66, L = 16
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 256 -K 168 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC_4}" --sim-pyber "Mesure_Diff_SPC_N_256_R_2_3_L_16_SPC4" > "mesures/Mesure_Diff_SPC_N_256_R_2_3_L_16_SPC4.txt"
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 256 -K 168 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC}" --sim-pyber "Mesure_Diff_SPC_N_256_R_2_3_L_16_SPC4+" > "mesures/Mesure_Diff_SPC_N_256_R_2_3_L_16_SPC4+.txt"
# # N = 1024, R = 0.66, L = 16
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 1024 -K 675 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC_4}" --sim-pyber "Mesure_Diff_SPC_N_1024_R_2_3_L_16_SPC4" > "mesures/Mesure_Diff_SPC_N_1024_R_2_3_L_16_SPC4.txt"
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 1024 -K 675 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC}" --sim-pyber "Mesure_Diff_SPC_N_1024_R_2_3_L_16_SPC4+" > "mesures/Mesure_Diff_SPC_N_1024_R_2_3_L_16_SPC4+.txt"
# # N = 4096, R = 0.66, L = 16
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 4096 -K 2703 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC_4}" --sim-pyber "Mesure_Diff_SPC_N_4096_R_2_3_L_16_SPC4" > "mesures/Mesure_Diff_SPC_N_4096_R_2_3_L_16_SPC4.txt"
./bin/aff3ct --sim-type BFER --sim-cde-type POLAR -m 0 -M 7 --src-type RAND --src-implem FAST  --chn-type AWGN --chn-implem FAST --dec-simd INTRA --crc-type FAST --crc-poly 32-GZIP -p 32 --enc-fb-gen-method GA --dec-type ASCL --sim-stats -e 100  --sim-no-colors -L 16 -N 4096 -K 2703 --dec-polar-nodes "{R0,R0L,R1,REP,REPL,SPC}" --sim-pyber "Mesure_Diff_SPC_N_4096_R_2_3_L_16_SPC4+" > "mesures/Mesure_Diff_SPC_N_4096_R_2_3_L_16_SPC4+.txt"
